# Generated by Django 5.2 on 2025-05-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quality',
            new_name='stock_quantity',
        ),
    ]
